[[kv_namespaces]]
binding = "ORDERS_KV"
id = "4602170a47ec41cea03eb42e2eb8e481"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "47cc0ed6a0ea4ac1a7f79458537bd4de"

[[r2_buckets]]
binding = "CUSTOM_UPLOADS"
bucket_name = "netsorna-custom-uploads"

# ADD THESE LINES:
[env.production]
vars = { ENVIRONMENT = "production" }

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"

[[routes]]
pattern = "*"
zone_name = ""
